<a href="https://colab.research.google.com/github/nicolez9911/colab/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

In [2]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.dtype)
print(scalar.dim())
print(scalar.shape)

tensor(7)
torch.int64
0
torch.Size([])


In [3]:
vector = torch.tensor([1,2])
print(vector.dtype)
print(vector.dim())
print(vector.shape)
vector

torch.int64
1
torch.Size([2])


tensor([1, 2])

In [4]:
matrix = torch.tensor([[1,2],[3,4]])
print(matrix.dim())
print(matrix.shape)
matrix

2
torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

### Creating Random Tensor

In [5]:
random_tensor = torch.rand(3, 2, 3)
random_tensor

tensor([[[0.5103, 0.6042, 0.6838],
         [0.7105, 0.6546, 0.7924]],

        [[0.7246, 0.2670, 0.1040],
         [0.0599, 0.9867, 0.7161]],

        [[0.0647, 0.3121, 0.5484],
         [0.4052, 0.3569, 0.8087]]])

In [6]:
random_tensor.ndim

3

In [7]:
random_tensor.shape

torch.Size([3, 2, 3])

### Zeros and ones

In [8]:
zeros = torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
zeros.dtype

torch.float32

In [10]:
ones = torch.ones(size=(3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### Creating a range of tensors and tensors-like

In [11]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
one_to_thirty = torch.arange(start=1, end=30, step=3)
one_to_thirty

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [13]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [14]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # set dtype, float32 is default
                               device=None, # cpu / gpu etc.
                               requires_grad=False # wheter or not to track gradient
                               )
float_32_tensor.dtype

torch.float32

In [15]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [16]:
converted = float_16_tensor.type(torch.float32)
converted.dtype

torch.float32

## Manipulating Tensors (tensor operation)

*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication







In [17]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [18]:
tensor - 5

tensor([-4, -3, -2])

In [19]:
torch.add(tensor, 5)

tensor([6, 7, 8])

In [20]:
tensor + 5

tensor([6, 7, 8])

In [21]:
tensor * tensor

tensor([1, 4, 9])

In [22]:
torch.matmul(tensor,tensor) # faster than a for loop

tensor(14)

In [23]:
# also works for matrix multiplication (but no so common)
tensor @ tensor

tensor(14)

In [24]:
tensor_test = torch.rand(3,2)

In [25]:
tensor_test, tensor_test.shape

(tensor([[0.2832, 0.0218],
         [0.1389, 0.5752],
         [0.5397, 0.5037]]),
 torch.Size([3, 2]))

In [26]:
tensor_test.T, tensor_test.T.shape

(tensor([[0.2832, 0.1389, 0.5397],
         [0.0218, 0.5752, 0.5037]]),
 torch.Size([2, 3]))

In [28]:
torch.mm(tensor_test, tensor_test)

RuntimeError: ignored

In [29]:
torch.mm(tensor_test, tensor_test.T)

tensor([[0.0807, 0.0519, 0.1639],
        [0.0519, 0.3501, 0.3647],
        [0.1639, 0.3647, 0.5450]])

## Finding min, max, mean & sum

In [30]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
torch.min(x)

tensor(0)

In [32]:
torch.max(x)

tensor(90)

In [33]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [34]:
# get index of the smallest element
torch.argmin(x)

tensor(0)

In [35]:
torch.argmax(x)

tensor(9)

In [36]:
x[torch.argmax(x)]

tensor(90)

## Reshaping, viewing and stacking

**view of a tensor shares the same memory, reshape makes a new one**

In [37]:
y = torch.arange(1.,11.)
y

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
y_reshaped = y.reshape(2, 5)
y_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [39]:
z = y.view(2, 5)
z

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [40]:
z[0] = 50.

In [41]:
z

tensor([[50., 50., 50., 50., 50.],
        [ 6.,  7.,  8.,  9., 10.]])

In [42]:
y

tensor([50., 50., 50., 50., 50.,  6.,  7.,  8.,  9., 10.])

In [43]:
y_stacked = torch.stack([x,y,x])
y_stacked

tensor([[ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
        [50., 50., 50., 50., 50.,  6.,  7.,  8.,  9., 10.],
        [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [44]:
y.shape

torch.Size([10])

In [45]:
y_squeezed = y.squeeze()
y_squeezed

tensor([50., 50., 50., 50., 50.,  6.,  7.,  8.,  9., 10.])

In [46]:
y_squeezed.shape

torch.Size([10])

### Permute

In [47]:
x_original = torch.rand(size=(224,224,3))

# permute to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)

In [48]:
x_original

tensor([[[0.7649, 0.4884, 0.1632],
         [0.4138, 0.5171, 0.8792],
         [0.9833, 0.1088, 0.0416],
         ...,
         [0.8882, 0.9149, 0.7383],
         [0.2074, 0.4167, 0.6507],
         [0.4441, 0.7647, 0.5797]],

        [[0.2878, 0.7139, 0.1399],
         [0.1092, 0.6651, 0.5091],
         [0.6769, 0.8984, 0.2988],
         ...,
         [0.1799, 0.3367, 0.3173],
         [0.8456, 0.6975, 0.3571],
         [0.9272, 0.8681, 0.1838]],

        [[0.6408, 0.8185, 0.6378],
         [0.6887, 0.1789, 0.0176],
         [0.7078, 0.5504, 0.2301],
         ...,
         [0.7205, 0.1902, 0.1388],
         [0.4195, 0.8003, 0.0834],
         [0.9276, 0.9462, 0.7021]],

        ...,

        [[0.7284, 0.2526, 0.9706],
         [0.9444, 0.3539, 0.2299],
         [0.3376, 0.6758, 0.3422],
         ...,
         [0.1009, 0.4582, 0.4376],
         [0.9609, 0.2120, 0.1367],
         [0.6536, 0.2148, 0.4910]],

        [[0.9669, 0.7928, 0.8663],
         [0.5154, 0.3769, 0.2844],
         [0.

In [49]:
x_permuted

tensor([[[0.7649, 0.4138, 0.9833,  ..., 0.8882, 0.2074, 0.4441],
         [0.2878, 0.1092, 0.6769,  ..., 0.1799, 0.8456, 0.9272],
         [0.6408, 0.6887, 0.7078,  ..., 0.7205, 0.4195, 0.9276],
         ...,
         [0.7284, 0.9444, 0.3376,  ..., 0.1009, 0.9609, 0.6536],
         [0.9669, 0.5154, 0.6764,  ..., 0.8539, 0.2316, 0.0897],
         [0.1586, 0.2603, 0.8853,  ..., 0.0126, 0.5700, 0.9024]],

        [[0.4884, 0.5171, 0.1088,  ..., 0.9149, 0.4167, 0.7647],
         [0.7139, 0.6651, 0.8984,  ..., 0.3367, 0.6975, 0.8681],
         [0.8185, 0.1789, 0.5504,  ..., 0.1902, 0.8003, 0.9462],
         ...,
         [0.2526, 0.3539, 0.6758,  ..., 0.4582, 0.2120, 0.2148],
         [0.7928, 0.3769, 0.2937,  ..., 0.5407, 0.2494, 0.0557],
         [0.4109, 0.6075, 0.4229,  ..., 0.5121, 0.5366, 0.6750]],

        [[0.1632, 0.8792, 0.0416,  ..., 0.7383, 0.6507, 0.5797],
         [0.1399, 0.5091, 0.2988,  ..., 0.3173, 0.3571, 0.1838],
         [0.6378, 0.0176, 0.2301,  ..., 0.1388, 0.0834, 0.

## Pytorch, Tensors and Numpy

In [50]:
a = np.arange(1.0, 8.0)
a

array([1., 2., 3., 4., 5., 6., 7.])

In [51]:
t = torch.from_numpy(a)
t

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [52]:
t.numpy() # > numpy array

array([1., 2., 3., 4., 5., 6., 7.])

## Reproducability

-> start with random numbers > tensor operations > update random numbers to try and make them better representation of the data -> again -> again ....

> random seed flavoured die randomness > dann hat man etwas mehr reproducability

In [53]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
rand1 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand2 = torch.rand(3,4)

rand1, rand2

(tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]),
 tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]))

In [54]:
!nvidia-smi

Tue Oct  3 14:09:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [56]:
torch.cuda.is_available()

True

In [57]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [58]:
torch.cuda.device_count()

1

In [59]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [60]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [64]:
tensor_on_gpu.numpy()

TypeError: ignored

In [62]:
# you cannot use numpy on gpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [63]:
tensor.numpy()

array([1, 2, 3])