<a href="https://colab.research.google.com/github/nicolez9911/colab/blob/main/mathofdl/Math_of_DL_L1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Mathematics of Deep Learning
## Lecture 1 Exercises
---
## 1. Computing the forward pass

Consider a neural network with the following architecture.

![Alt Text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz35Zhb7J5zGTwUiIP4zgjQCwztG37ZoEOWg&usqp=CAU)

We'll use as a data input the point $x = (1,2,3).$

In this exercise, you will practice intializing the weights and baises randomly and computing the forward pass.

Assume the hidden layer uses ReLU activation and that the output layer uses a sigmoid activation.

A network with 2-dimensional output given by sigmoid functions could be used, for example, to detect the presence of two different objects (ex. a car and/or a tree) in an image. An output of (1,1) means that the model detects both items with 100% certainty, while an output of (0,1) means the model doesn't detect the first item, but does detect the second.

In [3]:
x = np.array([1,2,3])

---
### Step 1: Randomly initialize the model parameters

In [24]:
# Use the np.random.randn function to intialize the weights and biases by
# sampling each component from a normal distribution.

# You should end up with:
#   W1 : a 4x3 array of weights for the first layer.
#   b1 : a 4D array of biases for the first layer.
#   W2: a 2x4 array of weights for the second layer.
#   b2 : a 2D array of biases for the second layer.

############################
# YOUR CODE HERE:
W1 = np.random.randn(3, 4)
b1 = np.random.randn(4, 1)
W2 = np.random.randn(4, 2)
b2 = np.random.randn(2, 1)

############################
W1, b1, W2, b2

(array([[-0.8195078 , -0.33701124, -0.89806547, -0.14414848],
        [ 2.07070057, -1.60016279, -0.69132874, -0.63841121],
        [ 0.56556242, -0.11964872,  0.16038102,  1.26468353]]),
 array([[ 0.64217211],
        [-0.19461406],
        [ 0.04393337],
        [ 0.37958282]]),
 array([[ 1.18747811,  0.3550394 ],
        [ 0.79659046, -0.4113674 ],
        [ 0.7686037 , -0.26712818],
        [ 0.67491771,  0.76504376]]),
 array([[ 0.68039343],
        [-0.42912448]]))

---
### Step 2: Define the sigmoid function.
Recall the defition of the sigmoid fucntion:
$$
\sigma(x) = \frac{1}{1+e^{-x}}.
$$

In [5]:
# Define a function that takes an input array x and computes the sigmoid
# function on each component.
# The expontential function is expressed in numpy as np.exp(x).

def sigmoid(x):
    '''
    x is an n-dimensional numpy array: [x0,x1,...,xn]

    returns sigmoidx = [sigmoid(x0),...,sigmoid(xn)]
    '''
    sigmoidx = 0
    ###### YOUR CODE HERE #####
    sigmoidx = 1 / (1 + np.exp(x))


    ###########################

    return sigmoidx

In [6]:
sigmoid(x)

array([0.26894142, 0.11920292, 0.04742587])

---
### Step 3: Compute the forward pass

Recall that the forward pass is computed

In [25]:
## Compute the forward pass.

# Your input is x = np.array([1,2,3]) and your output is a 2d-array.

# Hints: In numpy, the product of two matrices A*B is computed via A.dot(B).
# For the ReLU function, you can use np.maximum(0,x).


### YOUR CODE HERE ###
#y = np.maximum(0, W2.dot((W1.dot(x) + b1)) + b2)

(x.dot(W1) + b1).dot(W2) + b2

######################

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 

In [ ]:
# BONUS #

# Compute the forward pass for the following array corresponding to two input
# data samples given below. Your output should be a 2x2 array.

X = np.array([[1,2,3],[4,5,6]]).transpose()

# We must take the transpose because each data sample should correspond to a
# column vector. Numpy handles this automatically for 1D-arrays, but you have
# to be careful with 2D-arrays. You must also reshape b1 and b2 into
# column vectors.

b1 = b1.reshape(4,1)
b2 = b2.reshape(2,1)

### YOUR CODE HERE ###




######################

---
## 2. Computing the loss

Suppose we are training a binary classifier on a single sample. The model output is $\hat y = 0.7$. i.e. the model predicts a probability of 70% that the sample belongs in the class with the label '1.'

Suppose the sample actually belongs to the '0' class, and compute the corresponding log-loss:

$$L(y,\hat y) = -\frac{1}{n}\sum_{i=1}^{n}y_i\log \hat y_i + (1-y_i)\log(1-\hat y_i)$$

In [ ]:
## Compute the log-loss here:


In [ ]:
## BONUS ##

# Suppose the output layer in the NN from exercise 1 consists
# instead of a single node with sigmoid activation.

# Randomly initialize the weights and compute the corresponding loss
# for an input sample x = [1,1,1] with label y = 0.